spring.application.name=api-gateway

server.port=8080

spring.cloud.gateway.server.webmvc.routes[0].id=transaction-service
spring.cloud.gateway.server.webmvc.routes[0].uri=http://localhost:8083
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/transactions/**
spring.cloud.gateway.server.webmvc.routes[1].id=fraud-service
spring.cloud.gateway.server.webmvc.routes[1].uri=http://localhost:8081
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/fraud/**
spring.cloud.gateway.server.webmvc.globalcors.cors-configurations.[/**].allowedOrigins=http://localhost:5173
spring.cloud.gateway.server.webmvc.globalcors.cors-configurations.[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.server.webmvc.globalcors.cors-configurations.[/**].allowedHeaders=*
spring.cloud.gateway.server.webmvc.globalcors.add-to-simple-url-handler-mapping=true